package com.hnjiandao.dao;

import com.hnjiandao.domain.OverallDataBody;

public interface OverallDataBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    int deleteByPrimaryKey(String id);
    
    int deleteByOrderId(String headId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    int insert(OverallDataBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    int insertSelective(OverallDataBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    OverallDataBody selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    int updateByPrimaryKeySelective(OverallDataBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overall_data_body
     *
     * @mbggenerated Tue Aug 23 11:33:36 CST 2016
     */
    int updateByPrimaryKey(OverallDataBody record);
}