package com.hnjiandao.dao;

import java.util.List;

import com.hnjiandao.domain.Role;

public interface RoleMapper {
	/**
	 * 
	 * @return
	 */
    List<Role> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    Role selectByPrimaryKey(String id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Aug 31 14:21:07 CST 2016
     */
    int updateByPrimaryKey(Role record);
}