package com.hnjiandao.dao;

import java.util.List;

import com.hnjiandao.domain.UserTest;

public interface UserTestMapper {
    
	long count(UserTest userTest);
	
	List<UserTest> selectAll();
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    int insert(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    int insertSelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    UserTest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    int updateByPrimaryKeySelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    int updateByPrimaryKey(UserTest record);
}