package com.github.dao;

import com.github.domain.UserTest;
import com.github.domain.UserTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    long countByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    int deleteByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    int insert(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    int insertSelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    List<UserTest> selectByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserTest record, @Param("example") UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    int updateByExample(@Param("record") UserTest record, @Param("example") UserTestExample example);
}