package com.github.domain;

public class UserTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.user_name
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.password
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.id
     *
     * @return the value of user_test.id
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.id
     *
     * @param id the value for user_test.id
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.user_name
     *
     * @return the value of user_test.user_name
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.user_name
     *
     * @param userName the value for user_test.user_name
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.password
     *
     * @return the value of user_test.password
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.password
     *
     * @param password the value for user_test.password
     *
     * @mbg.generated Mon Jul 31 15:58:20 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}