package com.hnjiandao.domain;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.name
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.url
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.parent_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.name
     *
     * @return the value of permissions.name
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.name
     *
     * @param name the value for permissions.name
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.url
     *
     * @return the value of permissions.url
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.url
     *
     * @param url the value for permissions.url
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.parent_id
     *
     * @return the value of permissions.parent_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.parent_id
     *
     * @param parentId the value for permissions.parent_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.create_time
     *
     * @return the value of permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.create_time
     *
     * @param createTime the value for permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.update_time
     *
     * @return the value of permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.update_time
     *
     * @param updateTime the value for permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}