package com.hnjiandao.domain;

public class RolePermissionsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.permissions_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String permissionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param roleId the value for role_permissions.role_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.permissions_id
     *
     * @return the value of role_permissions.permissions_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.permissions_id
     *
     * @param permissionsId the value for role_permissions.permissions_id
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setPermissionsId(String permissionsId) {
        this.permissionsId = permissionsId == null ? null : permissionsId.trim();
    }
}