package com.hnjiandao.domain;

public class RolePermissions extends RolePermissionsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.create_time
     *
     * @return the value of role_permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.create_time
     *
     * @param createTime the value for role_permissions.create_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.update_time
     *
     * @return the value of role_permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.update_time
     *
     * @param updateTime the value for role_permissions.update_time
     *
     * @mbggenerated Fri Sep 02 15:20:24 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}