package com.hnjiandao.domain;

public class UserTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.name
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.id
     *
     * @return the value of user_test.id
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.id
     *
     * @param id the value for user_test.id
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.name
     *
     * @return the value of user_test.name
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.name
     *
     * @param name the value for user_test.name
     *
     * @mbggenerated Tue Aug 23 10:56:04 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}